<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/faq.css">
    <title> FAQs | </title>
    <link rel="icon" href="assets/img/tittle.png" type="image/icon type">
</head>

<body>

    <div class="container">
        <div class="header">
            <h3>FREQUENTLY ASKED QUESTIONS ON <br>ELECTRONIC VOTING MACHINES</h3>
        </div>

        <div class="col-md-12 mt-5">
        <ol>
            <li><b> What is an Electronic Voting machine? In what way its functioning is different from the
                    conventional system of voting? </b>
                <p>Ans. An Electronic Voting Machine consists of two Units – a Control Unit and a Balloting
                    Unit. Balloting unit has a five-meter cable, which is used to join the Control Unit with the
                    Balloting Unit. The Control Unit remains with the Presiding Officer or a Polling Officer and
                    the Balloting Unit is placed inside the voting compartment. The Polling Officer in-charge of
                    the Control Unit presses the ‘Ballot’ Button provided on the Control unit for releasing the
                    Ballot for the voter. It enables the voter to cast his vote by pressing the ‘Candidate’ button
                    (blue button) on the Balloting Unit against the candidate and symbol of his choice. </p>
            </li>

            <li><b> Who has devised the EVMs</b>
                <p>Ans. The EVMs have been devised and designed by Election Commission in collaboration
                    with two Public Sector undertakings i.e., Bharat Electronics Ltd., Bangalore (Ministry of
                    Defence) and Electronic Corporation of India Ltd., Hyderabad (Department of Atomic
                    Energy). </p>
            </li>


            <li><b>. How can EVMs be used in areas where there is no electricity?</b>
                <p>Ans. EVMs do not require electricity. EVMs run on an ordinary 7.5 volt alkaline Power -pack
                    (manufactured using 5 AA size cells of 1.5 volt each) supplied by Bharat Electronics Ltd.,
                    Bangalore and Electronic Corporation of India Ltd., Hyderabad. Therefore, even in areas
                    with no electricity connections, EVMs can be used. </p>
            </li>

            <li><b> What is the maximum number of votes, which can be cast in EVMs?</b>
                <p>A maximum of 3840 votes can be cast in old version EVMs (2000-05 model) and 2000
                    votes in case of new version EVMs (2006 onwards model).</p>
            </li>

            <li><b> What is the maximum number of candidates, which EVMs can cater to?</b>
                <p>Ans. EVMs can cater to a maximum of 64 candidates (including NOTA). There is provision for
                    16 candidates in one Balloting Unit. If the total number of candidates exceeds 16, a second
                    Balloting Unit can be linked in series to the first Balloting Unit. Similarly, if the total number
                    of candidates exceeds 32, a third Balloting Unit can be attached and if the total number of
                    candidates exceeds 48, a fourth Balloting Unit can be attached to cater to a maximum of 64
                    candidates (Including NOTA). In EVMs manufactured after 2013(Upgraded Post-2006
                    version) 24 Balloting units can be attached to one control unit catering to a maximum of 384
                    candidates (including NOTA). </p>
            </li>

            <li><b> What is the cost of the EVM? Is it not too expensive to use EVMs?</b>
                <p>Ans. The cost of one EVM (One Control Unit, one Balloting Unit)
                    1989-90 model EVM- Rs. 5,500/- per unit
                    2000-05 model EVM- Rs.8,670/- per unit
                    2006 onward model EVM- Rs. 8,670/- per unit (Tentative Cost)
                    ……..excluding excise duty, sales tax and transportation etc.
                    Even though the initial investment is somewhat high, this is subsequently neutralized by the
                    savings in the matter of printing of Ballot papers in lakhs, their transportation, storage etc.,
                    and the reduction in the counting staff and the remuneration paid to them. </p>
            </li>

            <li><b>In our country a sizeable section of the population being illiterate. Will it not cause
                    problems for the illiterate voters?</b>
                <p>Ans. In fact, voting by EVMs is simpler compared to the conventional system, where one has
                    to put the voting mark on or near the symbol of the candidate of his choice, fold it first
                    vertically and then horizontally and thereafter put it into the Ballot box. In EVMs, the voter
                    has to simply press the blue button against the name of the candidate and symbol of his
                    choice and the vote is recorded. Rural and illiterate people had no difficulty in recording
                    their votes and, in fact they have welcomed the use of EVMs.156 157 </p>
            </li>

            <li><b> With Ballot boxes counting is done after mixing the Ballot papers. Is it possible to
                    adopt this system when EVMs are used? </b>
                <p>Ans. Yes, it is possible by using a device named ‘Totalizer’. Totalizer can accommodate upto
                    14 control units at a time to count votes, without revealing the candidate-wise count of
                    individual control unit. But, presently this is not used because for using ‘Totalizer’
                    amendment in law is required. The same is pending with the Ministry of Law & Justice, Govt.
                    of India. </p>
            </li>

            <li><b> How long the Control Unit stores the result in its memory? </b>
                <p>Ans. The Control Unit can store the result in its memory for 10 years and even more. </p>
            </li>

            <li><b> Is it possible to vote more than once by pressing the button again and again?</b>
                <p>Ans. No. As soon as a particular button on the Balloting Unit is pressed, the vote is recorded
                    for that particular candidate and the machine gets locked. Even if one presses that button
                    further or any other button, no further vote can be recorded, unless ‘Ballot’ button provided
                    on the Control Unit is pressed to release the Ballot. This way the EVMs ensure the principle
                    of “one man, one vote”. </p>
            </li>

            <li><b>How can a voter be sure that the EVM is working properly and his vote has been
                    recorded correctly?</b>
                <p>As soon as the voter presses the `Candidate’ button (blue button) on the Balloting unit
                    against the name of the candidate and symbol of his choice, a tiny red lamp glows against
                    the name and symbol of the candidate for whom vote is cast and simultaneously a long
                    beep sound is heard. Thus, there are both audio and visual indications for the voter to be
                    assured that EVM is working properly and his vote has been recorded correctly.
                </p>
            </li>

            <li><b>In the conventional system, it will be possible to know the total number of votes
                    polled at any particular point of time. In EVMs ‘Result’ portion is sealed and will be
                    opened only at the time of counting. How can the total number of votes polled be known
                    on the date of poll?</b>
                <p>. In addition to the ‘Result’ button, there is a ‘Total’ button on EVMs. By pressing this
                    button the total number of votes polled upto the time of pressing the button will be
                    displayed without indicating the candidate-wise tally. </p>
            </li>

            <li><b>The Balloting Unit has provision for 16 candidates. In a constituency, there are only
                    10 candidates. If the voter presses any of the buttons from 11 to 16, will it not lead to
                    wastage of votes?</b>
                <p>Ans. No. If there are only 10 candidates in a constituency, the ‘Candidate’ buttons provided
                    at Sl. No. 11 to 16 shall be masked at the time of preparation of EVM by Returning Officer.
                    Therefore, there is no question of any voter pressing any of the buttons for candidates 11 to
                    16. </p>
            </li>
            <li><b> Ballot boxes are engraved so as to avoid any scope for complaint of replacement of
                    these boxes. Is there any system of numbering EVMs? </b>
                <p>Ans. Yes. Each Control Unit and Balloting Unit has a unique ID Number, which is engraved on
                    each unit. The list containing ID number of EVM (Balloting Unit & Control Unit) to be used in
                    a particular polling station is prepared and provided to the contesting candidates/their
                    agents. </p>
            </li>
            <li><b> In the conventional system, before the commencement of poll, the Presiding Officer
                    shows to the polling agents present there that the Ballot box to be used in the polling
                    station is empty. Is there any such provision to satisfy the polling agents that there are no
                    votes already recorded in the EVMs? </b>
                <p>Ans. Yes. Before the commencement of poll, the Presiding Officer demonstrates to the
                    polling agents that there is no vote already recorded in the machine by pressing the total
                    button. Thereafter, he conducts a mock poll by asking the polling agents to record their
                    votes and takes the result to satisfy them that the result shown is strictly according to the
                    choice recorded by them. Thereafter, the Presiding Officer presses the clear button. It clears
                    the result of the mock poll before commencing the actual poll. He then again shows to
                    polling agents, by pressing ‘Total’ button that it shows ‘0’. Then he seals the Control
                    Unit.158 159 </p>
            </li>
         
        </ol>
        </div>
    </div>
</body>

</html>